# Generated by Django 5.0.6 on 2024-06-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ImageField(default='https://fakeimg.pl/600x400', height_field=400, upload_to=None, width_field=400),
        ),
    ]
