# Generated by Django 5.0.6 on 2024-07-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images/uploads/'),
        ),
    ]
