# Generated by Django 5.0.6 on 2024-07-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_projects_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(default='default.png', upload_to='uploads/'),
        ),
    ]
